# add ci for gitlab
# stages : build, test

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm ci --legacy-peer-deps
    - npm run build
  only:
    - master

test:
  image: node:18
  stage: test
  script:
    - npm ci --legacy-peer-deps
    - npm run test
  only:
    - master
