version: '3.9'
services:
  videocuttool:
    container_name: videocuttool
    build:
      context: .
      dockerfile: Dockerfile.prd
    volumes:
      - ./src:/app/src:ro
      - ./server:/app/server
      - ./public:/app/public
      - '/app/node_modules'
    ports:
      - '80:80'
      - '4000:4000'
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://videocuttool:videocuttool@127.0.0.1:5432/videocuttool
      BACKEND_URL: https://videocuttool.wmcloud.org/api/
    env_file:
      - .env.prod
    depend_on:
      - database
  database:
    restart: unless-stopped
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: videocuttool
      POSTGRES_USER: videocuttool
      POSTGRES_DB: videocuttool
      PGDATA: /var/lib/postgresql/data/pg_data
    volumes:
      - ./postgres:/var/lib/postgresql/data
