version: '3.9'
services:
  videocuttool-server:
    restart: always
    container_name: videocuttool-server
    build:
      context: .
      dockerfile: Dockerfile.prd
    volumes:
      - ./src:/app/src:ro
      - ./server:/app/server
      - ./data/video-data/videos:/app/server/videos
      - ./data/video-data/public:/app/server/public
      - ./data/video-data/tmp:/app/server/tmp
      - '/app/node_modules'
      - /app/server/node_modules/
    environment:
      NODE_ENV: production
      DB_CONNECTION_URL: postgres://videocuttool:videocuttool@database:5432/videocuttool
    env_file:
      - .env.prod
    links:
      - database
    depends_on:
      - database
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
       - '80:80'
    links:
      - videocuttool-server
    depends_on:
      - videocuttool-server
  database:
    restart: unless-stopped
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: videocuttool
      POSTGRES_USER: videocuttool
      POSTGRES_DB: videocuttool
      PGDATA: /var/lib/postgresql/data/pg_data
    volumes:
      - ./data/postgresql-data:/var/lib/postgresql/data
